apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codespace-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "6000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "6000"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "6000"
  labels:
    app.kubernetes.io/name: codespace-ingress
spec:
  ingressClassName: nginx
  rules:
  -  http:
      paths:
      - pathType: Prefix
        path: "/api/sandbox"
        backend:
          service:
            name: sandbox-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/socket.io"
        backend:
          service:
            name: router-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/list-files"
        backend:
          service:
            name: router-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/read-files"
        backend:
          service:
            name: router-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/update-files"
        backend:
          service:
            name: router-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/create-file"
        backend:
          service:
            name: router-service
            port: 
              number: 80

  -  http:
      paths:
      - pathType: Prefix
        path: "/api/ai"
        backend:
          service:
            name: ai-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/api/auth"
        backend:
          service:
            name: auth-service
            port: 
              number: 80

  - host: "*.preview.13.127.231.53.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: router-service
            port: 
              number: 80

  - host: "*.agent.13.127.231.53.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: router-service
            port: 
              number: 80